# -*- coding: utf-8 -*-
"""Data_Analysis CA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUMzxO2UPM2ip3pOIQF-mc8TSsbfXY3w

You are required to develop a Data Acquisition and Preprocessing Pipeline of your choice, including data acquisition (API, Web scraping, DB Extract etc.), Extraction of features and Transformations as appropriate, followed by loading into an appropriate database. The focus of the complexity of the pipeline is your choice
"""

from bs4 import BeautifulSoup
import lxml
import requests
import pandas as pd
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

books = []
for i in range (1,51):
  url= f'https://books.toscrape.com/catalogue/page-{i}.html'
  response = requests.get(url)
  response = response.content
  soup = BeautifulSoup(response,'html.parser' )
  ol = soup.find('ol')
  articles=ol.find_all('article' , class_ ='product_pod' )

  for article in articles:
    image = article.find('img')
    title = image.attrs['alt']
    star = article.find ('p')
    star = star['class'][1]
    price = article.find('p',class_='price_color').text
    price = float(price [1: ])
    books.append([title,price,star])

df =pd.DataFrame(books, columns = ['Title','Price','Star Rating'])

df.to_csv('books.csv')

df

!curl ipecho.net/plain

!pip install 'pymongo [srv]'

import pymongo

